### ISSUE TITLE
Habit Tracking

### ISSUE THREAD

**Issue by jebwatson** [jebwatson/Intent#1]
As a user, I want a way to track my habits. This will involve:

- [x] displaying habits as a list, #2
- [x] persisting and retrieving habits, #3 
- [x] adding new habits, #4 
  - [x] setting habit title, #5 
  - [ ] setting habit interval, #6 
  - [ ] habit notes, #7 
- [x] updating habits, #8 
- [ ] deleting habits, #9 
- [ ] a way to indicate that a habit has been completed, #10 
- [ ] a way to indicate that a habit has been started, #11
